#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : flute.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sun Feb 10 20:27:53 PST 2019
# SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved. 
#
# usage: flute.sh [-help]
# usage: flute.sh [-lib_map_path]
# usage: flute.sh [-noclean_files]
# usage: flute.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'flute.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm xlconcat_v2_1_1 lib_cdc_v1_0_2 proc_sys_reset_v5_0_12 axi_infrastructure_v1_1_0 smartconnect_v1_0 axi_protocol_checker_v2_0_1 axi_vip_v1_1_1 processing_system7_vip_v1_0_3 axi_lite_ipif_v3_0_4 axi_intc_v4_1_10 xlslice_v1_0_1 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_15 fifo_generator_v13_2_1 axi_data_fifo_v2_1_14 axi_crossbar_v2_1_16 blk_mem_gen_v8_3_6 axi_bram_ctrl_v4_0_13 axi_protocol_converter_v2_1_15 axi_clock_converter_v2_1_14 blk_mem_gen_v8_4_1 axi_dwidth_converter_v2_1_15)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "flute.sh - Script generated by export_simulation (Vivado v2017.4 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "/data/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/data/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/data/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/data/opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_irqConcat_0/sim/flute_irqConcat_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_12 $vhdlan_opts \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_porReset_0/sim/flute_porReset_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_checker_v2_0_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/3b24/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_1 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/a16a/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_3 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_processing_system7_0_0/sim/flute_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_10 $vhdlan_opts \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/cf04/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_psInterruptController_0/sim/flute_psInterruptController_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/f3db/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_resetSlice_0/sim/flute_resetSlice_0.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_subprocessorClk_0/flute_subprocessorClk_0_mmcm_pll_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_subprocessorClk_0/proc_common_v3_00_a/hdl/src/vhdl/flute_subprocessorClk_0_conv_funs_pkg.vhd" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_subprocessorClk_0/proc_common_v3_00_a/hdl/src/vhdl/flute_subprocessorClk_0_proc_common_pkg.vhd" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_subprocessorClk_0/proc_common_v3_00_a/hdl/src/vhdl/flute_subprocessorClk_0_ipif_pkg.vhd" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_subprocessorClk_0/proc_common_v3_00_a/hdl/src/vhdl/flute_subprocessorClk_0_family_support.vhd" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_subprocessorClk_0/proc_common_v3_00_a/hdl/src/vhdl/flute_subprocessorClk_0_family.vhd" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_subprocessorClk_0/proc_common_v3_00_a/hdl/src/vhdl/flute_subprocessorClk_0_soft_reset.vhd" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_subprocessorClk_0/proc_common_v3_00_a/hdl/src/vhdl/flute_subprocessorClk_0_pselect_f.vhd" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_subprocessorClk_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/flute_subprocessorClk_0_address_decoder.vhd" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_subprocessorClk_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/flute_subprocessorClk_0_slave_attachment.vhd" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_subprocessorClk_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/flute_subprocessorClk_0_axi_lite_ipif.vhd" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_subprocessorClk_0/flute_subprocessorClk_0_clk_wiz_drp.vhd" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_subprocessorClk_0/flute_subprocessorClk_0_axi_clk_config.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_subprocessorClk_0/flute_subprocessorClk_0_clk_wiz.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_subprocessorClk_0/flute_subprocessorClk_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/3ed1/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/5c35/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_1 $vhdlan_opts \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/9909/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/c631/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_xbar_1/sim/flute_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_3_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/2751/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_0_13 $vhdlan_opts \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/20fd/hdl/axi_bram_ctrl_v4_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_procBramController_0/sim/flute_procBramController_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ff69/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_procProtocolConv_0/sim/flute_procProtocolConv_0.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_procXbar_0/sim/flute_procXbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_psBramController_0/sim/flute_psBramController_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_clock_converter_v2_1_14 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/445f/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_psClockConv_0/sim/flute_psClockConv_0.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_psCrossbar_0/sim/flute_psCrossbar_0.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_psProtocolConv_0/sim/flute_psProtocolConv_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_riscvBram_0/sim/flute_riscvBram_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_riscvReset_0/sim/flute_riscvReset_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_xbar_0/sim/flute_xbar_0.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/sim/flute.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec93/src/BRAM2.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec93/src/FIFO2.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec93/src/FIFO20.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec93/src/RegFile.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec93/src/mkBranch_Predictor.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec93/src/mkCPU.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec93/src/mkCSR_MIE.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec93/src/mkCSR_MIP.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec93/src/mkCSR_RegFile.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec93/src/mkGPR_RegFile.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec93/src/mkMMU_Cache.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec93/src/mkNear_Mem.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec93/src/mkNear_Mem_IO.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec93/src/mkRISCV_MBox.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec93/src/mkSoC_Map.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec93/src/mkCore.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_flute3_0_0/sim/flute_flute3_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_15 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1cdc/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/02c8/hdl/verilog" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/1313/hdl" +incdir+"$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ipshared/4868" +incdir+"/data/opt/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_auto_ds_1/sim/flute_auto_ds_1.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_auto_pc_1/sim/flute_auto_pc_1.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_auto_pc_2/sim/flute_auto_pc_2.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_auto_us_0/sim/flute_auto_us_0.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_auto_cc_0/sim/flute_auto_cc_0.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_auto_ds_0/sim/flute_auto_ds_0.v" \
    "$ref_dir/../../../../flute.srcs/sources_1/bd/flute/ip/flute_auto_pc_0/sim/flute_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.flute xil_defaultlib.glbl -o flute_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./flute_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./flute.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/iavendano/RISC-V-On-PYNQ/riscvonpynq/flute/tcm/flute/flute.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key flute_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc flute_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./flute.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: flute.sh [-help]\n\
Usage: flute.sh [-lib_map_path]\n\
Usage: flute.sh [-reset_run]\n\
Usage: flute.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
