# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/iavendano/RISC-V-On-PYNQ-Flute/riscvonpynq/picorv32/tut/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_porReset_0/tutorial_porReset_0.xci
# IP: The module: 'tutorial_porReset_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/iavendano/RISC-V-On-PYNQ-Flute/riscvonpynq/picorv32/tut/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_porReset_0/tutorial_porReset_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_porReset_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/iavendano/RISC-V-On-PYNQ-Flute/riscvonpynq/picorv32/tut/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_porReset_0/tutorial_porReset_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_porReset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/iavendano/RISC-V-On-PYNQ-Flute/riscvonpynq/picorv32/tut/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_porReset_0/tutorial_porReset_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_porReset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/iavendano/RISC-V-On-PYNQ-Flute/riscvonpynq/picorv32/tut/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_porReset_0/tutorial_porReset_0.xci
# IP: The module: 'tutorial_porReset_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/iavendano/RISC-V-On-PYNQ-Flute/riscvonpynq/picorv32/tut/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_porReset_0/tutorial_porReset_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_porReset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/iavendano/RISC-V-On-PYNQ-Flute/riscvonpynq/picorv32/tut/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_porReset_0/tutorial_porReset_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_porReset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/iavendano/RISC-V-On-PYNQ-Flute/riscvonpynq/picorv32/tut/tutorial/tutorial.srcs/sources_1/bd/tutorial/ip/tutorial_porReset_0/tutorial_porReset_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tutorial_porReset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
