# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/iavendano/RISC-V-On-PYNQ/riscvonpynq/PYNQ-Z1.xdc

# Block Designs: bd/flute/flute.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute || ORIG_REF_NAME==flute} -quiet] -quiet

# IP: bd/flute/ip/flute_irqAxiInterconnect_0/flute_irqAxiInterconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_irqAxiInterconnect_0 || ORIG_REF_NAME==flute_irqAxiInterconnect_0} -quiet] -quiet

# IP: bd/flute/ip/flute_irqConcat_0/flute_irqConcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_irqConcat_0 || ORIG_REF_NAME==flute_irqConcat_0} -quiet] -quiet

# IP: bd/flute/ip/flute_porReset_0/flute_porReset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_porReset_0 || ORIG_REF_NAME==flute_porReset_0} -quiet] -quiet

# IP: bd/flute/ip/flute_processing_system7_0_0/flute_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_processing_system7_0_0 || ORIG_REF_NAME==flute_processing_system7_0_0} -quiet] -quiet

# IP: bd/flute/ip/flute_psAxiInterconnect_0/flute_psAxiInterconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_psAxiInterconnect_0 || ORIG_REF_NAME==flute_psAxiInterconnect_0} -quiet] -quiet

# IP: bd/flute/ip/flute_psInterruptController_0/flute_psInterruptController_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_psInterruptController_0 || ORIG_REF_NAME==flute_psInterruptController_0} -quiet] -quiet

# IP: bd/flute/ip/flute_resetSlice_0/flute_resetSlice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_resetSlice_0 || ORIG_REF_NAME==flute_resetSlice_0} -quiet] -quiet

# IP: bd/flute/ip/flute_subprocessorClk_0/flute_subprocessorClk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_subprocessorClk_0 || ORIG_REF_NAME==flute_subprocessorClk_0} -quiet] -quiet

# IP: bd/flute/ip/flute_xbar_1/flute_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_xbar_1 || ORIG_REF_NAME==flute_xbar_1} -quiet] -quiet

# IP: bd/flute/ip/flute_procBramController_0/flute_procBramController_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_procBramController_0 || ORIG_REF_NAME==flute_procBramController_0} -quiet] -quiet

# IP: bd/flute/ip/flute_procProtocolConv_0/flute_procProtocolConv_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_procProtocolConv_0 || ORIG_REF_NAME==flute_procProtocolConv_0} -quiet] -quiet

# IP: bd/flute/ip/flute_procXbar_0/flute_procXbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_procXbar_0 || ORIG_REF_NAME==flute_procXbar_0} -quiet] -quiet

# IP: bd/flute/ip/flute_psBramController_0/flute_psBramController_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_psBramController_0 || ORIG_REF_NAME==flute_psBramController_0} -quiet] -quiet

# IP: bd/flute/ip/flute_psClockConv_0/flute_psClockConv_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_psClockConv_0 || ORIG_REF_NAME==flute_psClockConv_0} -quiet] -quiet

# IP: bd/flute/ip/flute_psCrossbar_0/flute_psCrossbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_psCrossbar_0 || ORIG_REF_NAME==flute_psCrossbar_0} -quiet] -quiet

# IP: bd/flute/ip/flute_psProtocolConv_0/flute_psProtocolConv_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_psProtocolConv_0 || ORIG_REF_NAME==flute_psProtocolConv_0} -quiet] -quiet

# IP: bd/flute/ip/flute_riscvBram_0/flute_riscvBram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_riscvBram_0 || ORIG_REF_NAME==flute_riscvBram_0} -quiet] -quiet

# IP: bd/flute/ip/flute_riscvReset_0/flute_riscvReset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_riscvReset_0 || ORIG_REF_NAME==flute_riscvReset_0} -quiet] -quiet

# IP: bd/flute/ip/flute_xbar_0/flute_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_xbar_0 || ORIG_REF_NAME==flute_xbar_0} -quiet] -quiet

# IP: bd/flute/ip/flute_flute3_0_0/flute_flute3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_flute3_0_0 || ORIG_REF_NAME==flute_flute3_0_0} -quiet] -quiet

# IP: bd/flute/ip/flute_auto_ds_1/flute_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_auto_ds_1 || ORIG_REF_NAME==flute_auto_ds_1} -quiet] -quiet

# IP: bd/flute/ip/flute_auto_pc_1/flute_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_auto_pc_1 || ORIG_REF_NAME==flute_auto_pc_1} -quiet] -quiet

# IP: bd/flute/ip/flute_auto_pc_2/flute_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_auto_pc_2 || ORIG_REF_NAME==flute_auto_pc_2} -quiet] -quiet

# IP: bd/flute/ip/flute_auto_us_0/flute_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_auto_us_0 || ORIG_REF_NAME==flute_auto_us_0} -quiet] -quiet

# IP: bd/flute/ip/flute_auto_cc_0/flute_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_auto_cc_0 || ORIG_REF_NAME==flute_auto_cc_0} -quiet] -quiet

# IP: bd/flute/ip/flute_auto_ds_0/flute_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_auto_ds_0 || ORIG_REF_NAME==flute_auto_ds_0} -quiet] -quiet

# IP: bd/flute/ip/flute_auto_pc_0/flute_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==flute_auto_pc_0 || ORIG_REF_NAME==flute_auto_pc_0} -quiet] -quiet

# XDC: bd/flute/flute_ooc.xdc
