# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/iavendano/RISC-V-On-PYNQ/riscvonpynq/microblaze/five/microblaze/microblaze.srcs/sources_1/bd/microblaze/ip/microblaze_ublaze_0/microblaze_ublaze_0.xci
# IP: The module: 'microblaze_ublaze_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/iavendano/RISC-V-On-PYNQ/riscvonpynq/microblaze/five/microblaze/microblaze.srcs/sources_1/bd/microblaze/ip/microblaze_ublaze_0/microblaze_ublaze_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_ublaze_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/iavendano/RISC-V-On-PYNQ/riscvonpynq/microblaze/five/microblaze/microblaze.srcs/sources_1/bd/microblaze/ip/microblaze_ublaze_0/microblaze_ublaze_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_ublaze_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/iavendano/RISC-V-On-PYNQ/riscvonpynq/microblaze/five/microblaze/microblaze.srcs/sources_1/bd/microblaze/ip/microblaze_ublaze_0/microblaze_ublaze_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_ublaze_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/iavendano/RISC-V-On-PYNQ/riscvonpynq/microblaze/five/microblaze/microblaze.srcs/sources_1/bd/microblaze/ip/microblaze_ublaze_0/microblaze_ublaze_0.xci
# IP: The module: 'microblaze_ublaze_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/iavendano/RISC-V-On-PYNQ/riscvonpynq/microblaze/five/microblaze/microblaze.srcs/sources_1/bd/microblaze/ip/microblaze_ublaze_0/microblaze_ublaze_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_ublaze_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/iavendano/RISC-V-On-PYNQ/riscvonpynq/microblaze/five/microblaze/microblaze.srcs/sources_1/bd/microblaze/ip/microblaze_ublaze_0/microblaze_ublaze_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_ublaze_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/iavendano/RISC-V-On-PYNQ/riscvonpynq/microblaze/five/microblaze/microblaze.srcs/sources_1/bd/microblaze/ip/microblaze_ublaze_0/microblaze_ublaze_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_ublaze_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
