# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/iavendano/RISC-V-On-PYNQ-Flute/riscvonpynq/PYNQ-Z1.xdc

# Block Designs: bd/tutorial/tutorial.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial || ORIG_REF_NAME==tutorial} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_irqConcat_0/tutorial_irqConcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_irqConcat_0 || ORIG_REF_NAME==tutorial_irqConcat_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_porReset_0/tutorial_porReset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_porReset_0 || ORIG_REF_NAME==tutorial_porReset_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_processing_system7_0_0/tutorial_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_processing_system7_0_0 || ORIG_REF_NAME==tutorial_processing_system7_0_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_psAxiInterconnect_0/tutorial_psAxiInterconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_psAxiInterconnect_0 || ORIG_REF_NAME==tutorial_psAxiInterconnect_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_psInterruptController_0/tutorial_psInterruptController_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_psInterruptController_0 || ORIG_REF_NAME==tutorial_psInterruptController_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_resetSlice_0/tutorial_resetSlice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_resetSlice_0 || ORIG_REF_NAME==tutorial_resetSlice_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_subprocessorClk_0/tutorial_subprocessorClk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_subprocessorClk_0 || ORIG_REF_NAME==tutorial_subprocessorClk_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_psBramController_0/tutorial_psBramController_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_psBramController_0 || ORIG_REF_NAME==tutorial_psBramController_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_riscvBram_0/tutorial_riscvBram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_riscvBram_0 || ORIG_REF_NAME==tutorial_riscvBram_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_riscvBramController_0/tutorial_riscvBramController_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_riscvBramController_0 || ORIG_REF_NAME==tutorial_riscvBramController_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_riscvReset_0/tutorial_riscvReset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_riscvReset_0 || ORIG_REF_NAME==tutorial_riscvReset_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_xbar_0/tutorial_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_xbar_0 || ORIG_REF_NAME==tutorial_xbar_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_auto_pc_1/tutorial_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_auto_pc_1 || ORIG_REF_NAME==tutorial_auto_pc_1} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_auto_pc_0/tutorial_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_auto_pc_0 || ORIG_REF_NAME==tutorial_auto_pc_0} -quiet] -quiet

# IP: bd/tutorial/ip/tutorial_auto_pc_2/tutorial_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tutorial_auto_pc_2 || ORIG_REF_NAME==tutorial_auto_pc_2} -quiet] -quiet

# XDC: bd/tutorial/tutorial_ooc.xdc
