# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/iavendano/RISC-V-On-PYNQ/riscvonpynq/PYNQ-Z1.xdc

# Block Designs: bd/microblaze/microblaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze || ORIG_REF_NAME==microblaze} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_irqAxiInterconnect_0/microblaze_irqAxiInterconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_irqAxiInterconnect_0 || ORIG_REF_NAME==microblaze_irqAxiInterconnect_0} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_irqConcat_0/microblaze_irqConcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_irqConcat_0 || ORIG_REF_NAME==microblaze_irqConcat_0} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_porReset_0/microblaze_porReset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_porReset_0 || ORIG_REF_NAME==microblaze_porReset_0} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_processing_system7_0_0/microblaze_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_processing_system7_0_0 || ORIG_REF_NAME==microblaze_processing_system7_0_0} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_psAxiInterconnect_0/microblaze_psAxiInterconnect_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_psAxiInterconnect_0 || ORIG_REF_NAME==microblaze_psAxiInterconnect_0} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_psInterruptController_0/microblaze_psInterruptController_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_psInterruptController_0 || ORIG_REF_NAME==microblaze_psInterruptController_0} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_softProcessorClk_0/microblaze_softProcessorClk_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_softProcessorClk_0 || ORIG_REF_NAME==microblaze_softProcessorClk_0} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_softProcessorResetSlice_0/microblaze_softProcessorResetSlice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_softProcessorResetSlice_0 || ORIG_REF_NAME==microblaze_softProcessorResetSlice_0} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_xbar_1/microblaze_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_xbar_1 || ORIG_REF_NAME==microblaze_xbar_1} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_psBramController_0/microblaze_psBramController_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_psBramController_0 || ORIG_REF_NAME==microblaze_psBramController_0} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_softProcessorBram_0/microblaze_softProcessorBram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_softProcessorBram_0 || ORIG_REF_NAME==microblaze_softProcessorBram_0} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_softProcessorLmbCtrl_0/microblaze_softProcessorLmbCtrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_softProcessorLmbCtrl_0 || ORIG_REF_NAME==microblaze_softProcessorLmbCtrl_0} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_softProcessorReset_0/microblaze_softProcessorReset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_softProcessorReset_0 || ORIG_REF_NAME==microblaze_softProcessorReset_0} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_ublaze_0/microblaze_ublaze_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_ublaze_0 || ORIG_REF_NAME==microblaze_ublaze_0} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_xbar_0/microblaze_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_xbar_0 || ORIG_REF_NAME==microblaze_xbar_0} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_auto_pc_1/microblaze_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_auto_pc_1 || ORIG_REF_NAME==microblaze_auto_pc_1} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_auto_pc_2/microblaze_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_auto_pc_2 || ORIG_REF_NAME==microblaze_auto_pc_2} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_auto_cc_0/microblaze_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_auto_cc_0 || ORIG_REF_NAME==microblaze_auto_cc_0} -quiet] -quiet

# IP: bd/microblaze/ip/microblaze_auto_pc_0/microblaze_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_auto_pc_0 || ORIG_REF_NAME==microblaze_auto_pc_0} -quiet] -quiet

# XDC: bd/microblaze/microblaze_ooc.xdc
