# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/iavendano/RISC-V-On-PYNQ/riscvonpynq/flute/tcm/flute/flute.srcs/sources_1/bd/flute/ip/flute_procProtocolConv_0/flute_procProtocolConv_0.xci
# IP: The module: 'flute_procProtocolConv_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/iavendano/RISC-V-On-PYNQ/riscvonpynq/flute/tcm/flute/flute.srcs/sources_1/bd/flute/ip/flute_procProtocolConv_0/flute_procProtocolConv_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'flute_procProtocolConv_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/iavendano/RISC-V-On-PYNQ/riscvonpynq/flute/tcm/flute/flute.srcs/sources_1/bd/flute/ip/flute_procProtocolConv_0/flute_procProtocolConv_0.xci
# IP: The module: 'flute_procProtocolConv_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/iavendano/RISC-V-On-PYNQ/riscvonpynq/flute/tcm/flute/flute.srcs/sources_1/bd/flute/ip/flute_procProtocolConv_0/flute_procProtocolConv_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'flute_procProtocolConv_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
